version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:30'
    open-pull-requests-limit: 5
    reviewers:
      - 'praveenskg'
    allow:
      - dependency-type: 'direct'
    labels:
      - 'dependencies'
      - 'automerge'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
      docusaurus:
        patterns:
          - '@docusaurus/*'
          - 'docusaurus'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:30'
    open-pull-requests-limit: 3
    reviewers:
      - 'praveenskg'
    labels:
      - 'dependencies'
      - 'automerge'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    groups:
      actions:
        patterns:
          - '*'
